### ISSUE TITLE
Mailwurm Belegungsplan 

### ISSUE THREAD

**Issue by Clumsy88** [Mailwurm/belegungsplan-bundle#11]
Contao 4.8 - 4.9.1

Die Anwendung Mailwurm Belegungsplan 2.4.6 lässt sich ohne Probleme installieren und einrichten. Beim erfassen der ersten Buchungszeit (Neue Buchungszeit) gibt es dann einen "internal Server Error" mit folgender Fehlermeldung:

An exception occurred while executing 'INSERT INTO tl_belegungsplan_calender (`author`, `pid`, `tstamp`) VALUES ('1', '1', 0)': SQLSTATE[HY000]: General error: 1364 Field 'ueberschneidung' doesn't have a default value

Im Forum hab ich auch schon eine mögliche Lösung gefunden:

"Wenn ich in der Datenbank beim Feld "ueberschneidung" in tl_belegungsplan_calender "erlaube NULL" anhake, funktioniert es."
--

**Frage: Wie komme ich an die Datenbank?** 

Vorab Danke für Eure Hilfe! 

Viele Grüße....

Magnus

**Comment by Clumsy88** [comment]
Schade, auch das Update auf Version 2.4.7 das dieses Problem nicht behoben...

An exception occurred while executing 'INSERT INTO tl_belegungsplan_calender (`author`, `dauer`, `pid`, `tstamp`) VALUES ('1', 'moreday', '3', 0)': SQLSTATE[HY000]: General error: 1364 Field 'ueberschneidung' doesn't have a default value

**Comment by Mailwurm** [comment]
Der Fehler lässt sich bei mir nicht reproduzieren und wie es scheint taucht das "Problem" nur bei Ihnen auf

**Comment by Clumsy88** [comment]
Nein, den Fehler gab´s schon mal! 

https://github.com/Mailwurm/belegungsplan-bundle/issues/2

Ich hab nur die Lösung nicht verstanden.

Neuinstallation/Update in meiner Installation hat alles nichts gebracht. Immer wenn ich bei einem Objekt eine "Neue Buchungszeit" erfassen möchte erscheint dieser Fehler.

**Comment by Clumsy88** [comment]
Problem erledigt mit der neusten Version (3.0)
