### ISSUE TITLE
Rechtschreibung

### ISSUE THREAD

**Issue by Aybee** [Mailwurm/belegungsplan-bundle#12]
Belegungspläne › Belegungszeiten ›

Länger **wie einen** Tag => Länger **als ein** Tag

Ist bei einem Vergleich das Ergebnis **gleich**, dann benutzt man "**(so) wie**".
Ist bei einem Vergleich das Ergebnis **unterschiedlich**, dann benutzt man "**als**".

Beispiele:
so groß wie, so gut wie, so lang wie
anders als, größer als, länger als

**Comment by Mailwurm** [comment]
Sie haben natürlich recht 🙄
