### ISSUE TITLE
FR: Minutenweise Buchung

### ISSUE THREAD

**Issue by Aybee** [Mailwurm/belegungsplan-bundle#13]
Hallo, danke für die Erweiterung. Planst du für die Zukunft eine Buchung auf Minutenbasis?

Ich benötige eigentlich eine Erweiterung für Sprechstunden in einer Praxis.

Gruß Andreas

**Comment by Mailwurm** [comment]
Hallo, für die Zukunft ist geplant Einzelbelegungspläne anzeigen zu lassen (momentan gibt es ja nur die Belegungpläne für alle Objekte) und einige doch hilfreiche Zusatzfunktionen zu integrieren. Eine Buchung auf Minutenbasis ist nicht geplant, dafür gibt es auch bereits eine Erweiterung. Einfach mal Googeln.
Grüsse Jan

**Comment by Aybee** [comment]
Ok, danke. Schade, weil ich sowas bräuchte. Gegoogelt hatte ich natürlich intensiv.
