### ISSUE TITLE
Abhängigkeit von patchwork/utf8 nicht in Composer.json

### ISSUE THREAD

**Issue by Olli** [Mailwurm/belegungsplan-bundle#19]
Version v3.0.1:
https://github.com/Mailwurm/belegungsplan-bundle/blob/master/src/Resources/contao/modules/ModuleBelegungsplan.php inkludiert 
patchwork/utf8 was aber nicht in der composer.json enthalten ist als Abhängigkeit.
Das führt dann im Contao zu einem Fehler wenn man den Artikel mit den Belegungsplänen aufrufen will im BE.

**Comment by RonnJohn** [comment]
Hallo,
gibt es dafür in der Zwischenzeit eine Lösung?

**Comment by mv-soft777** [comment]
Hallo,

ich erhalte unter CONTAO 4.13.43 die gleiche Fehlermeldung:

****************
Attempted to load class "Utf8" from namespace "Patchwork". Did you forget a "use" statement for another namespace?
****************

Gibt es eine Lösung dafür ?

Vielen Dank.

**Comment by zoglo** [comment]
For everyone that comes across this:
require the abandoned ```"patchwork/utf8": "v1.3.3"``` and you should be fine

**Comment by berecont** [comment]
Contao 4.13.45
php81
Belegungsplan Version v3.0.1

Ich bin heute über gleichen Fehler gestolpert. Habe jedoch `patchwork/utf8": "v1.3.3` nicht hinzugefügt, sondern eine Anpassung in der betroffenen Datei gemacht:

`vendor/mailwurm/belegungsplan-bundle/src/Resources/contao/modules/ModuleBelegungsplan.php`
Zeile 68 geändert auf:
`$objTemplate->wildcard = '### ' . mb_strtoupper($GLOBALS['TL_LANG']['FMD']['belegungsplan'][0], 'UTF-8') . ' ###';`

**Comment by Mailwurm** [comment]
Sollte in Version v4.0.0 behoben sein
