### ISSUE TITLE
Internal Server Error: Buchungszeit kann nicht eingetragen werden

### ISSUE THREAD

**Issue by hella-schu** [Mailwurm/belegungsplan-bundle#2]
Contao  4.4.30, belegungsplan-bundle 2.2.4

Beim Anlegen einer neuen Buchungszeit (klick auf "Neue Buchungszeit") gibt es einen Internal Server Error mit folgender Meldung:

`An exception occurred while executing 'INSERT INTO tl_belegungsplan_calender (`author`, `pid`, `tstamp`) VALUES ('1', '1', 0)': SQLSTATE[HY000]: General error: 1364 Field 'ueberschneidung' doesn't have a default value`

Viele Grüße
Hella

**Comment by hella-schu** [comment]
Wenn ich in der Datenbank beim Feld "ueberschneidung" in tl_belegungsplan_calender "erlaube NULL" anhake, funktioniert es.

**Comment by Clumsy88** [comment]
Hey Hella, 
wie komme ich dann an die Datenbank?
Danke für ein kurzes Feedback...
Magnus
