### ISSUE TITLE
Buchung am gleichen Tag: keine Ausgabe im Frontend!?

### ISSUE THREAD

**Issue by pswerbung** [Mailwurm/belegungsplan-bundle#4]
Wenn Anreise und Abreisetag identisch ist für eine Location-Buchung für schlicht nur 1 Tag, erfolgt keine Frontend-Ausgabe. Wie kann man dies ermöglichen?

**Comment by Mailwurm** [comment]
Hallo,

das ist korrekt.
Im Backend können Buchungen für einen Tag eingegeben werden.
Im Frontend hingegen werden zur Ausgabe dieses Tages zwei Tage angezeigt. Für das zu buchende Objekt ist es allerdings egal das zwei Tage zur Ausgabe verwendet werden, denn sollte für den nächsten Tag eine Buchung eingetragen werden, dann verlängert sich sich eben der rote durchgehende Balken um einen Tag.
Soll heißen, das am ersten angezeigten Tag die Location ausgebucht ist und das am zweiten angezeigten Tag der Besucher im Frontend sieht, das die Location für diesen Tag gebucht werden kann.
Ich hoffe das verständlich rüber gebracht zu haben, ansonsten einfach nochmal fragen.

Grüsse
