### ISSUE TITLE
Show more than current year

### ISSUE THREAD

**Issue by CAHro** [Mailwurm/belegungsplan-bundle#5]
Dear Mailwurm,

I'd like to show not only the current year, but also the bookings for the following year. I found no place to configure this.
Is there any possibility?

Sincerely 
Caro

**Comment by Mailwurm** [comment]
Hallo Caro,

wenn sie Buchungen für das Folgejahr eintragen, dann erscheint automatisch eine Auswahlbox zur Auswahl des Jahres. Der Seitenbesucher kann dann das Jahr auswählen, wo er die Buchungen anschauen möchte.
Prinzipiell werden alle Jahre in der Auswahlbox angezeigt für welche Buchungen eingetragen wurden, allerdings nur ab dem aktuellen Jahr.

Grüsse Jan
