### ISSUE TITLE
Fehlende clear Klasse

### ISSUE THREAD

**Issue by Olli** [Mailwurm/belegungsplan-bundle#6]
In der Ansicht, wo man das Objekt anlegen kann ist der Objektname nicht klickbar.
Das Infotext Widget liegt darüber weil dieses Widget keine .clear Klasse bekommen hat.

**Comment by Mailwurm** [comment]
Behoben in **[v2.4.6](https://github.com/Mailwurm/belegungsplan-bundle/releases/tag/v2.4.6)**
