### ISSUE TITLE
Bug - kein Sprung ins nächste Jahr möglich

### ISSUE THREAD

**Issue by Olli** [Mailwurm/belegungsplan-bundle#9]
Wenn Buchungen für das nächste jahr vorliegen, in diesem Jahr aber keine, wird das Sprungformular nicht angezeigt.

**Comment by Mailwurm** [comment]
Behoben in **[v2.4.6](https://github.com/Mailwurm/belegungsplan-bundle/releases/tag/v2.4.6)**
